# Generated by Django 5.0 on 2024-03-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pers', models.CharField(max_length=700)),
                ('prenom_pers', models.CharField(max_length=100)),
                ('tel_pers', models.CharField(max_length=15)),
                ('role_pers', models.CharField(max_length=15)),
                ('password_pers', models.CharField(max_length=10)),
            ],
        ),
    ]
