# Generated by Django 5.0 on 2024-04-16 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestCoopecphamApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='epargne',
            fields=[
                ('id_epargne', models.AutoField(primary_key=True, serialize=False)),
                ('montant_epargne', models.IntegerField()),
                ('ancien_solde', models.IntegerField()),
                ('nouveau_solde', models.IntegerField()),
                ('Date_epargne', models.DateField()),
                ('id_pers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestCoopecphamApp.personne')),
            ],
        ),
    ]
